<?php
session_start();
$roleId = (int) ($_SESSION['role_id'] ?? 0);
if (!in_array($roleId, [1, 2, 3], true)) {
    http_response_code(403);
    die('Access Denied');
}
$canManageDocuments = in_array($roleId, [1, 2], true);
include '../../layouts/header.php';
?>
<link rel="stylesheet" href="../../assets/css/dashboard.css?v=<?php echo filemtime(__DIR__ . '/../../assets/css/dashboard.css'); ?>">
<link rel="stylesheet" href="../../assets/css/documents.css?v=<?php echo filemtime(__DIR__ . '/../../assets/css/documents.css'); ?>">

<div class="dashboard-layout">
    <?php include '../../layouts/sidebar.php'; ?>
    <div class="main-content">
        <?php include '../../layouts/navbar.php'; ?>
        <div class="page-header">
            <div><h1>KP Documents</h1><p>Generate and retrieve official Katarungang Pambarangay forms.</p></div>
        </div>
        <div id="documentMessage" role="alert"></div>

        <?php if ($canManageDocuments): ?>
        <section class="document-card">
            <h2>KP Form 12 - Paabiso ng Pagdinig</h2>
            <p>Notice of Hearing for Conciliation Proceedings.</p>
            <form id="kp12Form">
                <input type="hidden" name="form_code" value="KP12">
                <div class="form-group">
                    <label for="documentCaseId">Case</label>
                    <select id="documentCaseId" name="case_id" required><option value="">Select a case</option></select>
                </div>
                <div id="kp12Preview" class="document-preview muted">Select a case to review the form data.</div>
                <div class="form-group">
                    <label for="noticeDate">Notice date</label>
                    <input type="date" id="noticeDate" name="notice_date" value="<?php echo date('Y-m-d'); ?>" required>
                </div>
                <button type="submit" class="btn-create">Generate KP Form 12 PDF</button>
            </form>
        </section>
        <?php endif; ?>

        <section class="document-card">
            <h2>Generated Documents</h2>
            <div class="table-container">
                <table><thead><tr><th>Form</th><th>Case</th><th>Complaint</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
                <tbody id="generatedDocumentsTable"></tbody></table>
            </div>
        </section>
    </div>
</div>
<script>
window.AGAP_DOCUMENTS = Object.freeze({ canManage: <?php echo $canManageDocuments ? 'true' : 'false'; ?> });
</script>
<script src="../../assets/js/documents.js?v=<?php echo filemtime(__DIR__ . '/../../assets/js/documents.js'); ?>"></script>
<?php include '../../layouts/footer.php'; ?>