<?php
session_start(); $roleId = (int) ($_SESSION['role_id'] ?? 0); if (!in_array($roleId, [1, 2, 4], true)) { http_response_code(403); die('Access Denied'); } include '../../layouts/header.php';
?>
<link rel="stylesheet" href="../../assets/css/gps.css?v=<?php echo filemtime(__DIR__ . '/../../assets/css/gps.css'); ?>">
<div class="dashboard-layout"><?php include '../../layouts/sidebar.php'; ?><div class="main-content"><?php include '../../layouts/navbar.php'; ?>
<div class="page-header"><div><h1>Proof of service</h1><p>Record field verification and notice delivery for active cases.</p></div></div><div id="proofMessage" role="alert"></div>
<section class="gps-card"><form id="proofForm" enctype="multipart/form-data"><div class="gps-grid"><div class="form-group"><label for="proofCaseId">Case</label><select id="proofCaseId" name="case_id" required><option value="">Select a case</option></select></div><div class="form-group"><label for="servedDate">Service date and time</label><input id="servedDate" type="datetime-local" name="served_date" required></div></div><div class="form-group"><label for="proofRemarks">Verification details</label><textarea id="proofRemarks" name="remarks" maxlength="2000" placeholder="Delivery result, recipient, or field observations"></textarea></div><div class="form-group"><label for="proofPhoto">Proof image (optional)</label><input id="proofPhoto" type="file" name="photo" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, or WebP up to 5 MB.</small></div><button class="btn-create" type="submit">Record proof of service</button></form></section>
<section class="gps-card"><h2>Service history</h2><p class="map-help">Choose a case to view its recorded service verification.</p><div class="table-container"><table><thead><tr><th>Served at</th><th>Recorded by</th><th>Verification details</th><th>Image</th></tr></thead><tbody id="proofsTable"></tbody></table></div></section>
</div></div><script src="../../assets/js/gps.js?v=<?php echo filemtime(__DIR__ . '/../../assets/js/gps.js'); ?>"></script><?php include '../../layouts/footer.php'; ?>
